name: Build TWRP Recovery

on:
  push:
    branches:
      - Twrp_12.1
  pull_request:
    branches:
      - Twrp_12.1

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up environment
      run: |
        sudo apt-get update
        sudo apt-get install -y git-core gnupg flex bison build-essential zip curl zlib1g-dev gcc-multilib g++-multilib \
        libc6-dev-i386 lib32ncurses5-dev x11proto-core-dev libx11-dev lib32z1-dev libgl1-mesa-dev libxml2-utils xsltproc \
        unzip fontconfig python3 python3-pip

    - name: Set up repo
      run: |
        mkdir -p ~/bin
        curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
        chmod a+x ~/bin/repo
        echo 'export PATH=~/bin:$PATH' >> ~/.bashrc
        source ~/.bashrc
        repo --version

    - name: Initialize TWRP source
      run: |
        repo init -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp.git -b twrp-12.1
        mkdir -p device/nubia/NX669J
        git clone https://github.com/piashmsubd/TWRP_NX669J_12.1 -b Twrp_12.1 device/nubia/NX669J

    - name: Sync source
      run: |
        repo sync -c -j$(nproc --all) --force-sync --no-clone-bundle --no-tags || repo sync -c -j$(nproc --all) --force-sync --no-clone-bundle --no-tags

    - name: Build TWRP
      run: |
        source build/envsetup.sh
        export ALLOW_MISSING_DEPENDENCIES=true
        export LC_ALL="C"
        lunch twrp_NX669J-eng
        mka recoveryimage

    - name: Upload recovery image
      uses: actions/upload-artifact@v3
      with:
        name: TWRP-NX669J
        path: out/target/product/NX669J/recovery.img
