name: Set Up SSH

on:
  push:
    branches:
      - main

jobs:
  ssh-setup:
    runs-on: ubuntu-latest

    steps:
    - name: Generate SSH Key
      run: |
        ssh-keygen -t rsa -b 4096 -C "github-actions@github.com" -f /home/runner/.ssh/id_rsa -N ""
        cat /home/runner/.ssh/id_rsa.pub

    - name: Add SSH Key to GitHub Secrets
      run: |
        echo "::add-mask::$(cat /home/runner/.ssh/id_rsa)"
        echo "::add-mask::$(cat /home/runner/.ssh/id_rsa.pub)"
        echo "SSH_PRIVATE_KEY=$(cat /home/runner/.ssh/id_rsa)" >> $GITHUB_ENV
        echo "SSH_PUBLIC_KEY=$(cat /home/runner/.ssh/id_rsa.pub)" >> $GITHUB_ENV

    - name: Upload SSH Key
      uses: actions/upload-artifact@v3
      with:
        name: ssh-key
        path: /home/runner/.ssh/id_rsa
