name: Clean GitHub Storage

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  clean:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Remove unnecessary files
      run: |
        echo "Removing unnecessary files..."
        find . -name "*.log" -type f -delete
        find . -name "*.tmp" -type f -delete

    - name: Run git gc
      run: |
        echo "Running git garbage collection..."
        git gc --prune=now --aggressive

    - name: Remove old branches and tags
      run: |
        echo "Removing old branches and tags..."
        git branch -r --merged | grep -v '\*' | grep -v 'main' | sed 's/origin\///' | xargs -n 1 git push origin --delete
        git tag -l | xargs -n 1 git push --delete origin
