name: Run SSH Command

on:
  push:
    branches:
      - main

jobs:
  run-ssh:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H github.com >> ~/.ssh/known_hosts

    - name: Run command on remote server
      env:
        RUNNER_IP: ${{ secrets.RUNNER_IP }}
      run: |
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa github-actions@${{ env.RUNNER_IP }} 'echo "Hello from GitHub Actions!"'
