name: Clean Workspace

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  clean:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Clean workspace
      run: |
        echo "Cleaning workspace..."
        rm -rf /path/to/your/workspace/*

    - name: Remove Docker images and containers
      run: |
        echo "Removing Docker images and containers..."
        docker system prune -a -f

    - name: Clean cache
      run: |
        echo "Cleaning cache..."
        rm -rf ~/.cache/*

    

    - name: Verify disk space
      run: |
        echo "Verifying disk space..."
        df -h
