name: Clean Root Space

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  clean:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Remove unnecessary packages
      run: |
        
         sudo rm -rf /repo

    - name: Remove old kernels
      run: |
        sudo apt-get remove --purge $(dpkg -l 'linux-*' | awk '/^ii/{ print $2}' | grep -E '[0-9]+\.[0-9]+\.[0-9]+' | grep -v $(uname -r))

    - name: Remove orphaned packages
      run: |
        sudo deborphan | xargs sudo apt-get -y remove --purge

    - name: Clear systemd journal logs
      run: |
        sudo journalctl --vacuum-time=2weeks

    - name: Remove unused Docker images and containers
      run: |
        docker system prune -a -f

    
    - name: Verify disk space
      run: |
        df -h
