name: EDK2 Build for NX669J

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build EDK2
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        submodules: true
        
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential uuid-dev iasl git nasm python3-distutils gcc-aarch64-linux-gnu acpica-tools python3 python3-pip
        
    - name: Clone EDK2
      run: |
        pwd
        git clone https://github.com/tianocore/edk2.git --recursive
        cd edk2
        git submodule update --init --recursive
        make -C BaseTools
        
    - name: Setup Environment
      run: |
        cd edk2
        . edksetup.sh BaseTools
        
    - name: Prepare Device Files
      run: |
        mkdir -p edk2/NX669J
        cp -v *.dsc edk2/NX669J/
        cp -v *.fdf edk2/NX669J/
        ls -la edk2/NX669J/
        
    - name: Build EDK2
      run: |
        cd edk2
        . edksetup.sh
        export WORKSPACE=$PWD
        export PACKAGES_PATH=$PWD:$PWD/NX669J
        export GCC5_AARCH64_PREFIX=aarch64-linux-gnu-
        build -a AARCH64 -t GCC5 -p NX669J/NX669J.dsc -b RELEASE
        ls -la Build/NX669J/RELEASE_GCC5/FV/
        
    - name: Debug Build Directory
      run: |
        echo "Checking Build Directory Contents:"
        ls -R Build/NX669J/
        
    - name: Upload Build
      uses: actions/upload-artifact@v3
      with:
        name: edk2-NX669J
        path: edk2/Build/NX669J/RELEASE_GCC5/FV/
