name: Full Clean Workspace

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  clean:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Clean workspace directories
      run: |
        echo "Cleaning workspace directories..."
        sudo rm -rf /path/to/your/workspace/*

    - name: Remove Docker images and containers
      run: |
        echo "Removing Docker images and containers..."
        sudo docker system prune -a -f

    - name: Clean cache directories
      run: |
        echo "Cleaning cache directories..."
        sudo rm -rf ~/.cache/*

    - name: Clean temporary files
      run: |
        echo "Cleaning temporary files..."
        sudo rm -rf /tmp/*
        sudo rm -rf /var/tmp/*

    - name: Verify disk space
      run: |
        echo "Verifying disk space..."
        df -h
