name: Build Kernel for Nubia SM8350

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Kernel Source
      uses: actions/checkout@v3
      with:
        repository: piashmsubd/android_kernel_nubia_sm8350  # আপনার কার্নেল সোর্স রেপো
        ref: lineage-20  # আপনার ব্রাঞ্চ নাম যদি ভিন্ন হয়, তাহলে সেটা দিন

    - name: Setup Dependencies
      run: |
        sudo apt update
        sudo apt install -y bc bison flex libssl-dev make gcc clang libncurses-dev

    - name: Setup GCC Cross-Compiler
      run: |
        wget https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9/+archive/refs/heads/master.tar.gz
        tar -xzf master.tar.gz
        export PATH=$PATH:$(pwd)/aarch64-linux-android-4.9/bin
        echo "Cross-Compiler setup completed"


    - name: Configure Kernel
      run: |
        export ARCH=arm64
        export SUBARCH=arm64
        export CROSS_COMPILE=aarch64-linux-android-4.9
        make nubia_defconfig  # আপনার ডিভাইসের সঠিক defconfig দিন

    - name: Build Kernel
      run: |
        make -j$(nproc)  # সব কোর ব্যবহার করে বিল্ড

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Kernel-Build
        path: arch/arm64/boot/Image.gz-dtb
