architecture: arm64
battery: {removable: False, capacity: 5050, tech: 'Li-Po'}
bluetooth: {spec: '5.1', profiles: [A2DP]}
brand: Nubia
camera:
  - {flash: 'LED', info: '64 MP'}
  - {flash: '', info: '8 MP (Ultra Wide)'}
  - {flash: '', info: '2 MP (Macro)'}
  - {flash: '', info: '8 MP (Front)'}
codename: redmagic6spro
cpu: Kryo 680
dimensions: {width: '77.1 mm', height: '169.9 mm', depth: '9.5 mm'}
download_boot: With the device powered off, hold <kbd>Volume Down</kbd> + <kbd>Power</kbd>.
gpu: Adreno 660
image: redmagic6spro.png
install_method: fastboot_nexus
kernel: android_kernel_nubia_sm8350
maintainers: [Your Name]
name: RedMagic 6S Pro
network: [2G GSM, 3G UMTS, 4G LTE, 5G]
peripherals: [Fingerprint reader, Accelerometer, Gyroscope, Proximity sensor, Compass, GPS]
ram: 8/12/16 GB
recovery_boot: With the device powered off, hold <kbd>Volume Up</kbd> + <kbd>Power</kbd>.
release: 2021-09
screen: {size: '6.8', density: 387, resolution: '2400x1080', technology: 'AMOLED'}
soc: Qualcomm SM8350 Snapdragon 888+
storage: 128/256 GB
tree: android_device_nubia_redmagic6spro
type: phone
vendor: Nubia
vendor_short: nubia
versions: [19.1]
wifi: {spec: 'Wi-Fi 6E', dual_band: True, hotspot: True}
