name: EDK2 Build for NX669J

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build EDK2
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        submodules: true
        
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential uuid-dev iasl git nasm python3-distutils gcc-aarch64-linux-gnu acpica-tools python3 python3-pip abootimg
        
    - name: Clone EDK2
      run: |
        git clone https://github.com/tianocore/edk2.git --recursive
        cd edk2
        git submodule update --init --recursive
        make -C BaseTools
        
    - name: Setup Files
      run: |
        mkdir -p edk2/NX669J
        cp -v *.dsc edk2/NX669J/
        cp -v *.fdf edk2/NX669J/
        ls -la edk2/NX669J/
        
    - name: Build EDK2
      run: |
        cd edk2
        . edksetup.sh
        export WORKSPACE=$PWD
        export PACKAGES_PATH=$PWD:$PWD/NX669J
        export GCC5_AARCH64_PREFIX=aarch64-linux-gnu-
        build -a AARCH64 -t GCC5 -p NX669J/NX669J.dsc -b RELEASE
        
    - name: Generate Boot Image
      run: |
        cd edk2/Build/NX669J/RELEASE_GCC5/FV
        mkdir -p tmp
        dd if=/dev/zero of=uefi.img bs=1M count=100
        mkfs.vfat uefi.img
        sudo mount uefi.img tmp/
        sudo cp *.efi tmp/
        sudo umount tmp/
        gzip -c uefi.img > uefi.img.gz
        abootimg --create boot.img -k uefi.img.gz -r /dev/null
        
    - name: Upload Build
      uses: actions/upload-artifact@v3
      with:
        name: edk2-NX669J
        path: |
          edk2/Build/NX669J/RELEASE_GCC5/FV/boot.img
          edk2/Build/NX669J/RELEASE_GCC5/FV/*.efi
        if-no-files-found: warn
