name: Full System Reset

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  reset:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Start full reset
      run: |
        echo "Starting full system reset..."

        # Remove all non-essential packages and files
        sudo apt-get remove --purge -y $(dpkg --get-selections | grep -v deinstall | awk '{print $1}')
        sudo apt-get autoremove -y
        sudo apt-get clean
        sudo rm -rf /var/lib/apt/lists/*

        # Clean temporary files
        sudo rm -rf /tmp/*
        sudo rm -rf /var/tmp/*

        # Clean Docker images and containers
        sudo docker system prune -a -f

        # Format and re-partition the root filesystem
        sudo mkfs.ext4 /dev/sda1
        
        # Reinstall essential packages
        sudo apt-get update
        sudo apt-get install -y build-essential curl wget

        echo "Full system reset completed. Please reboot the system."

    - name: Verify disk space
      run: |
        df -h
