# TWRP Build Configuration
name: TWRP_NX669J
description: "Custom TWRP Recovery for NX669J (RedMagic 6S)"
version: 12.1
maintainer: "Your Name (Dr.Brown28)"
github:
  repository: piashmsubd/TWRP_NX669J_12.1
  branch: Twrp_12.1
build:
  os: ubuntu-20.04
  arch: arm64
  commands:
    - . build/envsetup.sh
    - export ALLOW_MISSING_DEPENDENCIES=true
    - lunch twrp_NX669J-eng
    - mka recoveryimage
device:
  name: NX669J
  codename: NX669J
  manufacturer: Nubia
dependencies:
  - repo: https://github.com/TeamWin/android_bootable_recovery
    branch: android-12.1
  - repo: https://github.com/LineageOS/android_kernel_nubia_sm8350
    branch: lineage-19.1
  - repo: https://github.com/LineageOS/android_device_qcom_common
    branch: lineage-19.1
  - repo: https://github.com/TheMuppets/proprietary_vendor_nubia
    branch: lineage-19.1
build_output:
  path: out/target/product/NX669J/recovery.img
  format: img
upload:
  hosting: GitHub Releases
  repository: piashmsubd/TWRP_NX669J_12.1
  tag: "twrp-v12.1"
  release_name: "TWRP 12.1 for NX669J"
  description: |
    Custom TWRP Recovery for NX669J (RedMagic 6S).
    Features:
    - Android 12.1 support
    - File encryption/decryption
    - DTBO and A/B slot management
    - Stock ROM flashing support
    - Super unmap support
    - More customizations.
