name: EDK2 Build for NX669J

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential uuid-dev iasl git nasm python3-distutils gcc-aarch64-linux-gnu acpica-tools
        
    - name: Clone EDK2
      run: |
        git clone https://github.com/tianocore/edk2.git
        cd edk2
        git submodule update --init
        make -C BaseTools
        
    - name: Setup Build Files
      run: |
        mkdir -p edk2/NX669J
        cp NX669J.dsc edk2/NX669J/
        cp NX669J.fdf edk2/NX669J/
        
    - name: Build EDK2
      run: |
        cd edk2
        . edksetup.sh
        build -a AARCH64 -t GCC5 -p NX669J/NX669J.dsc -b RELEASE
        
    - name: Upload Build
      uses: actions/upload-artifact@v3
      with:
        name: edk2-NX669J
        path: edk2/Build/NX669J/RELEASE_GCC5/FV/
