name: EDK2 Build for NX669J

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build EDK2
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        submodules: recursive
      
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential uuid-dev iasl git nasm python3-distutils gcc-aarch64-linux-gnu acpica-tools
        
    - name: Clone EDK2
      run: |
        git clone https://github.com/tianocore/edk2.git --depth=1
        cd edk2
        git submodule update --init
        make -C BaseTools
        
    - name: Setup Build Environment
      run: |
        cd edk2
        . edksetup.sh
        export PACKAGES_PATH=$PWD:$PWD/../
        export GCC5_AARCH64_PREFIX=aarch64-linux-gnu-
        
    - name: Build Project
      run: |
        cd edk2
        build -a AARCH64 -t GCC5 -p NX669J/NX669J.dsc -b RELEASE
        
    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: edk2-NX669J
        path: edk2/Build/NX669J/RELEASE_GCC5/FV/
