name: EDK2 Build for NX669J

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build EDK2
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        submodules: true
        
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential uuid-dev iasl git nasm python3-distutils gcc-aarch64-linux-gnu acpica-tools python3 python3-pip
        
    - name: Clone EDK2
      run: |
        cd $GITHUB_WORKSPACE
        git clone https://github.com/tianocore/edk2.git --recursive
        cd edk2
        git submodule update --init --recursive
        make -C BaseTools
        . edksetup.sh
        
    - name: Copy Device Files
      run: |
        mkdir -p edk2/NX669J
        cp NX669J.dsc edk2/NX669J/
        cp NX669J.fdf edk2/NX669J/
        
    - name: Build EDK2
      run: |
        cd edk2
        . edksetup.sh
        build -a AARCH64 -t GCC5 -p NX669J/NX669J.dsc -b RELEASE
        
    - name: Upload Build
      uses: actions/upload-artifact@v3
      with:
        name: edk2-NX669J
        path: edk2/Build/NX669J/RELEASE_GCC5/FV/
