name: Build TWRP Recovery

on:
  push:
    branches:
      - Twrp_12.1
  pull_request:
    branches:
      - Twrp_12.1
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo dpkg --add-architecture i386
        sudo apt-get update
        sudo apt-get install -y git-core gnupg flex bison build-essential zip curl zlib1g-dev \
        gcc-multilib g++-multilib libc6-dev-i386 lib32ncurses5-dev x11proto-core-dev libx11-dev \
        lib32z1-dev libgl1-mesa-dev libxml2-utils xsltproc unzip fontconfig python3 python3-pip wget

    - name: Install Git-Repo
      run: |
        mkdir ~/bin
        curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
        chmod a+x ~/bin/repo
        sudo ln -sf ~/bin/repo /usr/bin/repo


    - name: Initialize repo
      run: |
        mkdir workspace
        cd workspace
        git config --global user.name "Samuel Kendall"
        git config --global user.email "kinguser981@gmail.com"
        repo init -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp.git -b twrp-12.1
        git clone --depth=1 https://github.com/piashmsubd/TWRP_NX669J_12.1.git -b Twrp_12.1 device/nubia/NX669J

    - name: Sync repo
      run: |
        repo sync -c -j$(nproc --all) --force-sync --no-clone-bundle --no-tags || repo sync -c -j$(nproc --all) --force-sync --no-clone-bundle --no-tags

    - name: Build TWRP
      run: |
        source build/envsetup.sh
        lunch twrp_NX669J-eng
        mka recoveryimage

    - name: Upload Recovery Image
      uses: actions/upload-artifact@v4
      with:
        name: twrp-recovery
        path: out/target/product/NX669J/recovery.img
