name: Build-TWRP
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Prepare the environment
        run: |
          sudo apt update
          sudo apt -y upgrade
          sudo apt -y install gperf gcc-multilib gcc-10-multilib g++-multilib g++-10-multilib libc6-dev-i386
          sudo apt -y install openjdk-8-jdk

      - name: Setup Git
        run: |
          git config --global user.name "আপনার নাম"
          git config --global user.email "আপনার ইমেইল"

      - name: Install repo tool
        run: |
          mkdir -p ~/bin
          curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
          chmod a+x ~/bin/repo
          sudo ln -sf ~/bin/repo /usr/bin/repo

      - name: Initialize repo
        run: |
          mkdir workspace
          cd workspace
          repo init --depth=1 -u https://github.com/piashmsubd/android_manifest -b main
          mkdir -p .repo/local_manifests
          echo '<manifest>
            <project name="piashmsubd/android_device_nubia_NX669J" path="device/nubia/NX669J" remote="github" revision="master" />
          </manifest>' > .repo/local_manifests/roomservice.xml

      - name: Repo Sync
        run: |
          cd workspace
          repo sync -j$(nproc --all) --force-sync

      - name: Setup build environment
        run: |
          cd workspace
          source build/envsetup.sh
          lunch twrp_NX669J-eng

      - name: Build TWRP
        run: |
          cd workspace
          mka recoveryimage
